name: Aliyun Signin

on:
  schedule:
   # 每天国际时间 14:40 运行一次, 中国时间 22:40
    - cron: '40 14 * * *'
  workflow_dispatch:
jobs:
  signin:
    name: Aliyun Signin
    runs-on: ubuntu-latest
    steps:
      - uses: ImYrS/aliyun-auto-signin@main
        with:
          REFRESH_TOKENS: {"default_sbox_drive_id":"88767121","role":"user","device_id":"686ff50fc1994721ba1314770f08fdde","user_name":"138***193","need_link":false,"expire_time":"2023-08-04T03:46:10Z","pin_setup":false,"need_rp_verify":false,"avatar":"","token_type":"Bearer","access_token":"eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJhNzQ5ZDllZGJjZjg0ZjQ1OWQwZTk0MzE2OTE1NjAxOCIsImN1c3RvbUpzb24iOiJ7XCJjbGllbnRJZFwiOlwiMjVkelgzdmJZcWt0Vnh5WFwiLFwiZG9tYWluSWRcIjpcImJqMjlcIixcInNjb3BlXCI6W1wiRFJJVkUuQUxMXCIsXCJTSEFSRS5BTExcIixcIkZJTEUuQUxMXCIsXCJVU0VSLkFMTFwiLFwiVklFVy5BTExcIixcIlNUT1JBR0UuQUxMXCIsXCJTVE9SQUdFRklMRS5MSVNUXCIsXCJCQVRDSFwiLFwiT0FVVEguQUxMXCIsXCJJTUFHRS5BTExcIixcIklOVklURS5BTExcIixcIkFDQ09VTlQuQUxMXCIsXCJTWU5DTUFQUElORy5MSVNUXCIsXCJTWU5DTUFQUElORy5ERUxFVEVcIl0sXCJyb2xlXCI6XCJ1c2VyXCIsXCJyZWZcIjpcImh0dHBzOi8vd3d3LmFsaXl1bmRyaXZlLmNvbS9cIixcImRldmljZV9pZFwiOlwiZWI5YjUxODc3ZjE2NGM5ZGJiZjIwOWExOTM0ZjVlYmVcIn0iLCJleHAiOjE2OTExMjA3NzAsImlhdCI6MTY5MTExMzUxMH0.JoP6pPKChQxFAEuhnKoGIoo155Y22eLzF5EUyxgSs83O1KnVgZzUEMJsOVRMN_HzNNKyrYExJANBba2BOVREDd_bDUKwULVQMGFTb-2PFJKLoCsorR45MeVKeoXy_0I223cEvGYN7mFfBhSNTDM36lbioKyJe3gtLhxtjqotVtM","default_drive_id":"78767121","domain_id":"bj29","refresh_token":"eb9b51877f164c9dbbf209a1934f5ebe","is_first_login":false,"hlogin_url":"https://passport.aliyundrive.com/unity_login_dispatcher.htm?tokenType=aliyun_drive&token=CN-SPLIT-AQilxojzr0AQ2AQiD3VuaXR5VHJ1c3RMb2dpbioMYWxpeXVuX2RyaXZlMgEBOJ2E5fGbMUABShDb1_hAzKPFxZY9n8Y1zRlHc72TcPm-bpZMd9jfzMtBAtBZTt4&bizScene=REFRESH_SELF&cid=MjEzNjgxNzgyYzNjNDFjYTk2MTc5MTViNzlkMjBkM2E","user_id":"a749d9edbcf84f459d0e943169156018","nick_name":"","exist_link":[],"state":"","expires_in":7200,"status":"enabled"}
          GP_TOKEN: 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
          PUSH_TYPES: ''
          DO_NOT_REWARD: 'false'
          SERVERCHAN_SEND_KEY: ${{ secrets.SERVERCHAN_SEND_KEY }}
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          PUSHPLUS_TOKEN: ${{ secrets.PUSHPLUS_TOKEN }}
          PUSHPLUS_TOPIC: ${{ secrets.PUSHPLUS_TOPIC }}
          SMTP_HOST: ${{ secrets.SMTP_HOST }}
          SMTP_PORT: ${{ secrets.SMTP_PORT }}
          SMTP_TLS: ${{ secrets.SMTP_TLS }}
          SMTP_USER: ${{ secrets.SMTP_USER }}
          SMTP_PASSWORD: ${{ secrets.SMTP_PASSWORD }}
          SMTP_SENDER: ${{ secrets.SMTP_SENDER }}
          SMTP_RECEIVER: ${{ secrets.SMTP_RECEIVER }}
          FEISHU_WEBHOOK: ${{ secrets.FEISHU_WEBHOOK }}
          WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}
          CQHTTP_ENDPOINT: ${{ secrets.CQHTTP_ENDPOINT }}
          CQHTTP_USER_ID: ${{ secrets.CQHTTP_USER_ID }}
          CQHTTP_ACCESS_TOKEN: ${{ secrets.CQHTTP_ACCESS_TOKEN }}
